//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: initial_environment.proto

package com.kyhsgeekcode.minecraft_env.proto;

@kotlin.jvm.JvmName("-initializeblockState")
public inline fun blockState(block: com.kyhsgeekcode.minecraft_env.proto.BlockStateKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.InitialEnvironment.BlockState =
  com.kyhsgeekcode.minecraft_env.proto.BlockStateKt.Dsl._create(com.kyhsgeekcode.minecraft_env.proto.InitialEnvironment.BlockState.newBuilder()).apply { block() }._build()
public object BlockStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraft_env.proto.InitialEnvironment.BlockState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraft_env.proto.InitialEnvironment.BlockState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraft_env.proto.InitialEnvironment.BlockState = _builder.build()

    /**
     * <code>int32 x = 1;</code>
     */
    public var x: kotlin.Int
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <code>int32 x = 1;</code>
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * <code>int32 y = 2;</code>
     */
    public var y: kotlin.Int
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <code>int32 y = 2;</code>
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * <code>int32 z = 3;</code>
     */
    public var z: kotlin.Int
      @JvmName("getZ")
      get() = _builder.getZ()
      @JvmName("setZ")
      set(value) {
        _builder.setZ(value)
      }
    /**
     * <code>int32 z = 3;</code>
     */
    public fun clearZ() {
      _builder.clearZ()
    }

    /**
     * <pre>
     * minecraft:andesite_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
     * </pre>
     *
     * <code>string block_state = 4;</code>
     */
    public var blockState: kotlin.String
      @JvmName("getBlockState")
      get() = _builder.getBlockState()
      @JvmName("setBlockState")
      set(value) {
        _builder.setBlockState(value)
      }
    /**
     * <pre>
     * minecraft:andesite_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
     * </pre>
     *
     * <code>string block_state = 4;</code>
     */
    public fun clearBlockState() {
      _builder.clearBlockState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraft_env.proto.InitialEnvironment.BlockState.copy(block: com.kyhsgeekcode.minecraft_env.proto.BlockStateKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.InitialEnvironment.BlockState =
  com.kyhsgeekcode.minecraft_env.proto.BlockStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

