//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: observation_space.proto

package com.kyhsgeekcode.minecraft_env.proto;

@kotlin.jvm.JvmName("-initializeentityInfo")
public inline fun entityInfo(block: com.kyhsgeekcode.minecraft_env.proto.EntityInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo =
  com.kyhsgeekcode.minecraft_env.proto.EntityInfoKt.Dsl._create(com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo.newBuilder()).apply { block() }._build()
public object EntityInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo = _builder.build()

    /**
     * <code>string unique_name = 1;</code>
     */
    public var uniqueName: kotlin.String
      @JvmName("getUniqueName")
      get() = _builder.getUniqueName()
      @JvmName("setUniqueName")
      set(value) {
        _builder.setUniqueName(value)
      }
    /**
     * <code>string unique_name = 1;</code>
     */
    public fun clearUniqueName() {
      _builder.clearUniqueName()
    }

    /**
     * <code>string translation_key = 2;</code>
     */
    public var translationKey: kotlin.String
      @JvmName("getTranslationKey")
      get() = _builder.getTranslationKey()
      @JvmName("setTranslationKey")
      set(value) {
        _builder.setTranslationKey(value)
      }
    /**
     * <code>string translation_key = 2;</code>
     */
    public fun clearTranslationKey() {
      _builder.clearTranslationKey()
    }

    /**
     * <code>double x = 3;</code>
     */
    public var x: kotlin.Double
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <code>double x = 3;</code>
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * <code>double y = 4;</code>
     */
    public var y: kotlin.Double
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <code>double y = 4;</code>
     */
    public fun clearY() {
      _builder.clearY()
    }

    /**
     * <code>double z = 5;</code>
     */
    public var z: kotlin.Double
      @JvmName("getZ")
      get() = _builder.getZ()
      @JvmName("setZ")
      set(value) {
        _builder.setZ(value)
      }
    /**
     * <code>double z = 5;</code>
     */
    public fun clearZ() {
      _builder.clearZ()
    }

    /**
     * <code>double yaw = 6;</code>
     */
    public var yaw: kotlin.Double
      @JvmName("getYaw")
      get() = _builder.getYaw()
      @JvmName("setYaw")
      set(value) {
        _builder.setYaw(value)
      }
    /**
     * <code>double yaw = 6;</code>
     */
    public fun clearYaw() {
      _builder.clearYaw()
    }

    /**
     * <code>double pitch = 7;</code>
     */
    public var pitch: kotlin.Double
      @JvmName("getPitch")
      get() = _builder.getPitch()
      @JvmName("setPitch")
      set(value) {
        _builder.setPitch(value)
      }
    /**
     * <code>double pitch = 7;</code>
     */
    public fun clearPitch() {
      _builder.clearPitch()
    }

    /**
     * <code>double health = 8;</code>
     */
    public var health: kotlin.Double
      @JvmName("getHealth")
      get() = _builder.getHealth()
      @JvmName("setHealth")
      set(value) {
        _builder.setHealth(value)
      }
    /**
     * <code>double health = 8;</code>
     */
    public fun clearHealth() {
      _builder.clearHealth()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo.copy(block: com.kyhsgeekcode.minecraft_env.proto.EntityInfoKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo =
  com.kyhsgeekcode.minecraft_env.proto.EntityInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

