//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: observation_space.proto

package com.kyhsgeekcode.minecraft_env.proto;

@kotlin.jvm.JvmName("-initializehitResult")
public inline fun hitResult(block: com.kyhsgeekcode.minecraft_env.proto.HitResultKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult =
  com.kyhsgeekcode.minecraft_env.proto.HitResultKt.Dsl._create(com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult.newBuilder()).apply { block() }._build()
public object HitResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult = _builder.build()

    /**
     * <code>.HitResult.Type type = 1;</code>
     */
    public var type: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult.Type
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>.HitResult.Type type = 1;</code>
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>.BlockInfo target_block = 2;</code>
     */
    public var targetBlock: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BlockInfo
      @JvmName("getTargetBlock")
      get() = _builder.getTargetBlock()
      @JvmName("setTargetBlock")
      set(value) {
        _builder.setTargetBlock(value)
      }
    /**
     * <code>.BlockInfo target_block = 2;</code>
     */
    public fun clearTargetBlock() {
      _builder.clearTargetBlock()
    }
    /**
     * <code>.BlockInfo target_block = 2;</code>
     * @return Whether the targetBlock field is set.
     */
    public fun hasTargetBlock(): kotlin.Boolean {
      return _builder.hasTargetBlock()
    }

    /**
     * <code>.EntityInfo target_entity = 3;</code>
     */
    public var targetEntity: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo
      @JvmName("getTargetEntity")
      get() = _builder.getTargetEntity()
      @JvmName("setTargetEntity")
      set(value) {
        _builder.setTargetEntity(value)
      }
    /**
     * <code>.EntityInfo target_entity = 3;</code>
     */
    public fun clearTargetEntity() {
      _builder.clearTargetEntity()
    }
    /**
     * <code>.EntityInfo target_entity = 3;</code>
     * @return Whether the targetEntity field is set.
     */
    public fun hasTargetEntity(): kotlin.Boolean {
      return _builder.hasTargetEntity()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult.copy(block: com.kyhsgeekcode.minecraft_env.proto.HitResultKt.Dsl.() -> kotlin.Unit): com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResult =
  com.kyhsgeekcode.minecraft_env.proto.HitResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResultOrBuilder.targetBlockOrNull: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.BlockInfo?
  get() = if (hasTargetBlock()) getTargetBlock() else null

public val com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.HitResultOrBuilder.targetEntityOrNull: com.kyhsgeekcode.minecraft_env.proto.ObservationSpace.EntityInfo?
  get() = if (hasTargetEntity()) getTargetEntity() else null

